spring:
  application:
    name: ocean-backend

  datasource:
    # 아직 RDS 엔드포인트(주소)가 안 나왔으니 일단 비워둡니다. 나중에 채울 겁니다.
    url: jdbc:mysql://[RDS엔드포인트]:3306/smart_sourcing_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: wjddnjswns  # 아까 설정한 비번
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 서버 켜질 때 DB 테이블 자동 생성
    properties:
      hibernate:
        format_sql: true # 로그 예쁘게 보기

server:
  port: 8080